services:
  - type: web
    name: group-management-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: API_TOKEN
        sync: false
