services:
  - type: web
    name: group-management-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8000
